---
title: "Numeric"
author: "Dipankar Lahiri"
date: "2025-03-06"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library (dplyr)
library (readr)
library (ggplot2)

my_df <- read_csv ('life-under-lockdown-wave2-extract.csv')

knowledge_levels <- c('Nothing at all', 'Not very much', 'A fair amount', 'A great deal')

my_df <- my_df %>%
  mutate(
    know_facebook = know_facebook %>%
      ordered(
        levels = knowledge_levels
      )
  )
```

``` {r visualise age}

my_df %>%
  ggplot (
    aes (x=age)
  ) +
  geom_histogram(binwidth = 5)
```

```{r visualise gender}

my_df %>%
  ggplot (
    aes(x = gender)
  ) +
  geom_bar()

```
```{r - visualise facebook}

my_df %>%
  ggplot (
    aes(x=know_facebook)
  ) +
  geom_bar()

```
``` {r}
my_df %>%
  ggplot(
    aes(x=beliefs)
  ) + geom_histogram(binwidth = 1)
```

# Gender vs beliefs

``` {r gender vs beliefs}

my_df %>%
  group_by(gender) %>%
  summarise (n = n(), M = mean (beliefs), Mdn = median (beliefs), SD = sd (beliefs))
```

``` {r gender-vs-beliefs-test}
my_df %>%
  filter(gender == "Male" | gender == "Female") %>%
  t.test(
    beliefs ~ gender,
    data = .
  )
```

In the sample, men (M = 0.73, SD = 1.13) had more misinformation beliefs than women (M = 0.61, SD = 1.05). But this difference was not statistically significant, t(494.31) = -1.20, p = 0.230.
